-- Migration: Create user_skill table
-- Description: User skills with level and uniqueness constraint

CREATE TYPE skill_level_enum AS ENUM ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT');

CREATE TABLE public.user_skill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.app_user(id) ON DELETE CASCADE,
    skill_name TEXT NOT NULL CHECK (char_length(skill_name) >= 1 AND char_length(skill_name) <= 100),
    skill_level skill_level_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_user_skill UNIQUE (user_id, skill_name)
);

CREATE INDEX idx_user_skill_user_id ON public.user_skill(user_id);
CREATE INDEX idx_user_skill_skill_name ON public.user_skill(skill_name);

-- Enable RLS
ALTER TABLE public.user_skill ENABLE ROW LEVEL SECURITY;

-- Policies
-- Authenticated users can read all skills (for teammate discovery)
CREATE POLICY "Authenticated can read all skills"
    ON public.user_skill FOR SELECT
    TO authenticated
    USING (true);

-- Users can only manage their own skills
-- We need to check ownership via app_user.auth_user_id = auth.uid()
CREATE POLICY "Users can insert own skills"
    ON public.user_skill FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.app_user
            WHERE app_user.id = user_skill.user_id
            AND app_user.auth_user_id = auth.uid()
        )
    );

CREATE POLICY "Users can delete own skills"
    ON public.user_skill FOR DELETE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.app_user
            WHERE app_user.id = user_skill.user_id
            AND app_user.auth_user_id = auth.uid()
        )
    );

-- For updates if needed in future (though we use DELETE+INSERT pattern)
CREATE POLICY "Users can update own skills"
    ON public.user_skill FOR UPDATE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.app_user
            WHERE app_user.id = user_skill.user_id
            AND app_user.auth_user_id = auth.uid()
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.app_user
            WHERE app_user.id = user_skill.user_id
            AND app_user.auth_user_id = auth.uid()
        )
    );

COMMENT ON TABLE public.user_skill IS 'User skills - owned by app_user, unique per user+skill_name';
