-- Migration: Create Hackathon Hub tables
-- Description: hackathon, hackathon_skill, saved_hackathon, and hackathon_reminder tables with constraints, indexes, and RLS

-- 1. Create hackathon table
CREATE TABLE public.hackathon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (char_length(name) >= 2 AND char_length(name) <= 200),
    organizer TEXT NOT NULL CHECK (char_length(organizer) >= 2 AND char_length(organizer) <= 200),
    description TEXT NOT NULL,
    banner_url TEXT,
    registration_url TEXT NOT NULL,
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    registration_deadline TIMESTAMPTZ NOT NULL,
    location TEXT NOT NULL DEFAULT 'Online',
    mode TEXT NOT NULL CHECK (mode IN ('ONLINE', 'OFFLINE', 'HYBRID')),
    prize_pool BIGINT NOT NULL DEFAULT 0 CHECK (prize_pool >= 0),
    team_size_min INTEGER NOT NULL DEFAULT 1 CHECK (team_size_min >= 1),
    team_size_max INTEGER NOT NULL DEFAULT 4 CHECK (team_size_max >= team_size_min),
    eligibility TEXT,
    difficulty TEXT NOT NULL CHECK (difficulty IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED')),
    status TEXT NOT NULL DEFAULT 'UPCOMING' CHECK (status IN ('UPCOMING', 'OPEN', 'ONGOING', 'COMPLETED', 'CANCELLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Trigger for hackathon updated_at
CREATE TRIGGER set_hackathon_updated_at
    BEFORE UPDATE ON public.hackathon
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Indexes on hackathon
CREATE INDEX idx_hackathon_registration_deadline ON public.hackathon(registration_deadline);
CREATE INDEX idx_hackathon_start_date ON public.hackathon(start_date);
CREATE INDEX idx_hackathon_status ON public.hackathon(status);
CREATE INDEX idx_hackathon_mode ON public.hackathon(mode);
CREATE INDEX idx_hackathon_organizer ON public.hackathon(organizer);

-- 2. Create hackathon_skill table
CREATE TABLE public.hackathon_skill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hackathon_id BIGINT NOT NULL REFERENCES public.hackathon(id) ON DELETE CASCADE,
    skill_name TEXT NOT NULL CHECK (char_length(skill_name) >= 1 AND char_length(skill_name) <= 100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_hackathon_skill UNIQUE (hackathon_id, skill_name)
);

CREATE INDEX idx_hackathon_skill_hackathon_id ON public.hackathon_skill(hackathon_id);
CREATE INDEX idx_hackathon_skill_skill_name ON public.hackathon_skill(skill_name);

-- 3. Create saved_hackathon table
CREATE TABLE public.saved_hackathon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.app_user(id) ON DELETE CASCADE,
    hackathon_id BIGINT NOT NULL REFERENCES public.hackathon(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_saved_hackathon UNIQUE (user_id, hackathon_id)
);

CREATE INDEX idx_saved_hackathon_user_id ON public.saved_hackathon(user_id);
CREATE INDEX idx_saved_hackathon_hackathon_id ON public.saved_hackathon(hackathon_id);

-- 4. Create hackathon_reminder table
CREATE TABLE public.hackathon_reminder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.app_user(id) ON DELETE CASCADE,
    hackathon_id BIGINT NOT NULL REFERENCES public.hackathon(id) ON DELETE CASCADE,
    reminder_type TEXT NOT NULL CHECK (reminder_type IN ('REGISTRATION_DEADLINE', 'HACKATHON_START', 'HACKATHON_END')),
    reminder_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_hackathon_reminder UNIQUE (user_id, hackathon_id, reminder_type)
);

CREATE INDEX idx_hackathon_reminder_user_id ON public.hackathon_reminder(user_id);
CREATE INDEX idx_hackathon_reminder_hackathon_id ON public.hackathon_reminder(hackathon_id);
CREATE INDEX idx_hackathon_reminder_reminder_at ON public.hackathon_reminder(reminder_at);

-- Row Level Security (RLS)
ALTER TABLE public.hackathon ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hackathon_skill ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_hackathon ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hackathon_reminder ENABLE ROW LEVEL SECURITY;

-- Hackathon read policy
CREATE POLICY "Authenticated users can read hackathons"
    ON public.hackathon FOR SELECT
    TO authenticated
    USING (true);

-- Hackathon skill read policy
CREATE POLICY "Authenticated users can read hackathon skills"
    ON public.hackathon_skill FOR SELECT
    TO authenticated
    USING (true);

-- Saved hackathons policies
CREATE POLICY "Users can read own saved hackathons"
    ON public.saved_hackathon FOR SELECT
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.app_user
            WHERE app_user.id = saved_hackathon.user_id
            AND app_user.auth_user_id = auth.uid()
        )
    );

CREATE POLICY "Users can insert own saved hackathons"
    ON public.saved_hackathon FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.app_user
            WHERE app_user.id = saved_hackathon.user_id
            AND app_user.auth_user_id = auth.uid()
        )
    );

CREATE POLICY "Users can delete own saved hackathons"
    ON public.saved_hackathon FOR DELETE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.app_user
            WHERE app_user.id = saved_hackathon.user_id
            AND app_user.auth_user_id = auth.uid()
        )
    );

-- Hackathon reminders policies
CREATE POLICY "Users can read own reminders"
    ON public.hackathon_reminder FOR SELECT
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.app_user
            WHERE app_user.id = hackathon_reminder.user_id
            AND app_user.auth_user_id = auth.uid()
        )
    );

CREATE POLICY "Users can insert own reminders"
    ON public.hackathon_reminder FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.app_user
            WHERE app_user.id = hackathon_reminder.user_id
            AND app_user.auth_user_id = auth.uid()
        )
    );

CREATE POLICY "Users can delete own reminders"
    ON public.hackathon_reminder FOR DELETE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.app_user
            WHERE app_user.id = hackathon_reminder.user_id
            AND app_user.auth_user_id = auth.uid()
        )
    );
