-- Migration: Create app_user table
-- Description: Foundational user profile table linked to Supabase auth.users

-- Enable UUID extension if not already
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create app_user table
CREATE TABLE public.app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id UUID NOT NULL UNIQUE,
    display_name TEXT NOT NULL CHECK (char_length(display_name) >= 2 AND char_length(display_name) <= 100),
    bio TEXT CHECK (char_length(bio) <= 1000),
    college TEXT CHECK (char_length(college) <= 200),
    course TEXT CHECK (char_length(course) <= 200),
    year_of_study INTEGER CHECK (year_of_study >= 1 AND year_of_study <= 10),
    experience_level TEXT CHECK (experience_level IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_auth_user FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX idx_app_user_auth_user_id ON public.app_user(auth_user_id);
CREATE INDEX idx_app_user_display_name ON public.app_user(display_name);

-- Updated_at trigger
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_app_user_updated_at
    BEFORE UPDATE ON public.app_user
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Enable RLS
ALTER TABLE public.app_user ENABLE ROW LEVEL SECURITY;

-- RLS Policies - defense in depth, backend uses service_role but frontend anon should be restricted
-- Policy: Users can view their own profile via auth.uid() = auth_user_id
-- For now, allow authenticated users to read all profiles (for future teammate discovery)
-- But restrict write to own profile only

-- Allow all authenticated to read profiles (needed for collaboration)
CREATE POLICY "Authenticated users can read all profiles"
    ON public.app_user FOR SELECT
    TO authenticated
    USING (true);

-- Allow users to insert their own profile only
CREATE POLICY "Users can insert own profile"
    ON public.app_user FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = auth_user_id);

-- Allow users to update own profile only
CREATE POLICY "Users can update own profile"
    ON public.app_user FOR UPDATE
    TO authenticated
    USING (auth.uid() = auth_user_id)
    WITH CHECK (auth.uid() = auth_user_id);

-- Allow users to delete own profile only (or admin - handled via service_role)
CREATE POLICY "Users can delete own profile"
    ON public.app_user FOR DELETE
    TO authenticated
    USING (auth.uid() = auth_user_id);

-- Service role bypasses RLS automatically, so backend with service_role key can manage all

COMMENT ON TABLE public.app_user IS 'Application user profiles linked to Supabase auth.users';
COMMENT ON COLUMN public.app_user.auth_user_id IS 'FK to auth.users.id - Supabase Auth owns authentication';
